default: &default
  encoding: unicode
  adapter: postgresql

development:
  <<: *default
  database: ruby-docs-generator-dev

test:
  <<: *default
  database: ruby-docs-generator-test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
