default: &default
  encoding: unicode
  adapter: postgresql

development:
  <<: *default
  database: ruby-docs-generator-dev

test:
  <<: *default
  database: ruby-docs-generator-test

production:
  <<: *default
  username: ruby-docs-generator
  database: ruby-docs-generator-production
  password: <%= ENV['RUBY_DOCS_GENERATOR_DATABASE_PASSWORD'] %>
