default: &default
  encoding: unicode
  adapter: postgresql

development:
  <<: *default
  database: ruby-docs-generator-dev
  username: postgres
  password: 123456

test:
  <<: *default
  database: ruby-docs-generator-test
  username: postgres
  password: 123456
  
production:
  <<: *default
  username: ruby-docs-generator
  database: ruby-docs-generator-production
  password: <%= ENV['RUBY_DOCS_GENERATOR_DATABASE_PASSWORD'] %>
