default: &default
  encoding: unicode
  adapter: postgresql

development:
  <<: *default
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: ruby-docs-generator-dev


test:
  <<: *default
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: ruby-docs-generator-test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
